diff -u -r1.23 Makefile.common
--- Makefile.common	17 Feb 2004 01:39:07 -0000	1.23
+++ Makefile.common	13 Aug 2004 17:52:41 -0000
@@ -84,7 +84,7 @@
 # ----------------------------------------------------------------------------
 
 # options
-COPT  =-O2 -fno-builtin -fomit-frame-pointer
+COPT  =-g -O2 -fno-builtin -fomit-frame-pointer
 CWARN =-Wall
 #
 # 2000.03.12 - Paolo Masetti <paolo.masetti@itlug.org>
diff -u -r1.9 Makefile.user
--- Makefile.user	14 Feb 2003 05:48:49 -0000	1.9
+++ Makefile.user	13 Aug 2004 17:52:41 -0000
@@ -62,6 +62,10 @@
 %.lx: %.ds1 %.ds2
 	$(MAKELX) $*.ds1 $*.ds2 $@
 
+#  How to make library files (.a) for brickemu
+%.a: %.o $(DOBJECTS)
+	@rm -f $@
+	$(AR) r $@ $*.o $(DOBJECTS)
 
 ### --------------------------------------------------------------------------
 ###                          End of FILE: Makefile.user
diff -u -r1.20 Makefile
--- boot/Makefile	17 Feb 2004 01:39:07 -0000	1.20
+++ boot/Makefile	13 Aug 2004 17:52:41 -0000
@@ -13,7 +13,7 @@
          timeout.c dkey.c dmotor.c dsensor.c dsound.c swmux.c\
          atomic.c critsec.c setjmp.c
 
-KERNEL_TARGETS = $(KERNEL).srec \
+KERNEL_TARGETS = $(KERNEL).coff $(KERNEL).srec \
                  $(KERNEL).lds
 
 #
