name: brickEmu CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: update apt-get
      run: sudo apt-get --assume-yes update
    - name: install build dependencies
      run: sudo apt-get --assume-yes install binutils-h8300-hms gcc-h8300-hms libz-dev libsdl-sound1.2-dev
    - name: make
      run: make
